module.exports = [
  {
    slug: 'input',
    id: 'image-id',
    label: 'id',
    placeholder: 'Picture-25',
    type: 'text',
    name: 'image-id',
  },
  {
    slug: 'input',
    id: 'image-label',
    label: 'label',
    placeholder: 'Paris',
    type: 'text',
    name: 'image-label',
  },
  {
    slug: 'input',
    id: 'image-title',
    label: 'Title',
    placeholder: 'Splintered Voyager',
    type: 'text',
    name: 'image-title',
  },
  {
    slug: 'input',
    id: 'image-url',
    label: 'url',
    placeholder: '/img-25',
    type: 'text',
    name: 'image-url',
  },
  {
    slug: 'input',
    id: 'image-alt',
    label: 'alt',
    placeholder: 'Girl with bag',
    type: 'text',
    name: 'image-alt',
  },
  {
    slug: 'textarea',
    id: 'image-desc',
    label: 'Description',
    placeholder:
      'Sequi in eaque omnis provident et temporibus autem in. Magni laborum veniam laudantium quod illo quaerat modi autem voluptas. Maiores eveniet architecto quibusdam cumque est. Reiciendis dolores eius minus commodi',
    type: 'text',
    name: 'image-desc',
  },
]
